# Jacobin project Github Action v. 1.0 -- 18 May 2021
name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
#    - name: Run tests
#      run: swift test -v
